# scripts/generate_report.py
import json
import numpy as np
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCORES_FILE = ROOT / "metadata" / "phoneme_similarity_scores.json"
TIMESTAMPS_FILE = ROOT / "metadata" / "phoneme_timestamps.json"
OUT_FILE = ROOT / "metadata" / "assessment_report.json"

# --- CONFIGURATION ---
# Short consonants are naturally harder to capture, so we grade them on a curve.
SHORT_SOUNDS = ["P", "B", "T", "D", "K", "G", "F", "V", "TH", "DH", "S", "Z", "SH", "ZH", "CH", "JH"]

def get_grade(score):
    """Converts a normalized score (0-100) into a grade."""
    if score >= 70: return "Good", "green"
    if score >= 40: return "Average", "yellow"
    return "Needs Improvement", "red"

def normalize_score(raw_sim, phoneme):
    """
    Calibrated Teacher Logic for Non-Native Speakers.
    """
    # 1. Clamp negative to 0
    score = max(0.0, raw_sim)
    
    # 2. Stronger Boost for Consonants
    # "Strict Math" sees 0.40 as bad. "Human Teacher" sees 0.40 as Good for 'K' or 'T'.
    if phoneme in SHORT_SOUNDS:
        # Formula: y = x^0.5 (Square Root Curve) - Very forgiving for low numbers
        # 0.10 -> 0.31
        # 0.25 -> 0.50
        # 0.40 -> 0.63 (Green)
        score = np.power(score, 0.5)
    else:
        # Vowels: Linear scaling but boosted 
        # 0.60 -> 0.76
        # 0.70 -> 0.85
        score = (score * 0.8) + 0.2 if score > 0.1 else score

    # 3. Scale to 0-100
    final_score = int(score * 100)
    
    # Cap at 100
    return min(100, final_score)

# def normalize_score(raw_sim, phoneme):
#     """
#     Calibrated for SILERO TTS
#     """
#     # 1. Clamp to 0
#     score = max(0.0, raw_sim)
    
#     # 2. Boost Logic
#     if phoneme in SHORT_SOUNDS:
#         # Curve for Consonants (T, K, P, etc.)
#         # If raw is 0.15 -> Boost to ~0.50 (Yellow)
#         # Formula: y = x^0.4
#         score = np.power(score, 0.4)
#     else:
#         # Curve for Vowels
#         # If raw is 0.30 -> Boost to ~0.65 (Yellow/Green boundary)
#         # Formula: y = x^0.55
#         score = np.power(score, 0.55)

#     # 3. Scale 0-100
#     final_score = int(score * 100)
    
#     # Safety cap
#     return min(100, final_score)

def main():
    if not SCORES_FILE.exists() or not TIMESTAMPS_FILE.exists():
        print("[ERROR] Missing input files. Run compare_phonemes.py and align_phonemes_dtw.py first.")
        return

    with open(SCORES_FILE, "r") as f:
        raw_data = json.load(f)
        # Create a lookup map: "filepath" -> score
        # We assume file paths in JSON match the ones generated by slice_phonemes
        # We need to normalize paths to avoid slash issues
        score_map = {}
        for item in raw_data["per_slice"]:
            # extract "0003_hello_OW1" from path
            fname = Path(item["file"]).name
            score_map[fname] = item["similarity"]

    with open(TIMESTAMPS_FILE, "r") as f:
        # This contains the word/phoneme structure ordered by time
        alignment_data = json.load(f)

    final_report = {
        "overall_score": 0,
        "details": []
    }

    total_score = 0
    count = 0

    # Group by word
    current_word_idx = -1
    current_word_obj = None

    for entry in alignment_data:
        w_idx = entry["word_index"]
        word_text = entry["word"]
        ph = entry["phoneme"]
        
        # New word group?
        if w_idx != current_word_idx:
            if current_word_obj:
                # Calculate word average before pushing
                w_scores = [p["score"] for p in current_word_obj["phonemes"]]
                current_word_obj["word_score"] = int(np.mean(w_scores)) if w_scores else 0
                grade, color = get_grade(current_word_obj["word_score"])
                current_word_obj["grade"] = grade
                current_word_obj["color"] = color
                final_report["details"].append(current_word_obj)

            current_word_idx = w_idx
            current_word_obj = {
                "word": word_text,
                "word_score": 0,
                "phonemes": []
            }

        # Construct filename key to look up score
        # slice_phonemes.py naming: f"{i:04d}_{safe_word}_{p['phoneme']}.wav"
        # We need to reconstruct the index 'i' relative to the full list?
        # Actually, let's just match loosely or assume 'alignment_data' order matches 'score_map'?
        # Better: slice_phonemes used a global counter. We need to match that.
        # FIX: The score_map keys look like "0000_hello_HH.wav". 
        # We can just match by "word" and "phoneme" if unique, or we need to track index.
        # Let's rely on the fact that slice_phonemes iterates exactly like alignment_data.
        
        # We need the global index `count` to match filenames like 0000_...
        safe_word = "".join(c for c in word_text if c.isalnum() or c in ("_","-")).lower()
        fname = f"{count:04d}_{safe_word}_{ph}.wav"
        
        raw_sim = score_map.get(fname, 0.0) # Default to 0 if missing
        
        # Normalize
        final_score = normalize_score(raw_sim, ph)
        grade, color = get_grade(final_score)

        current_word_obj["phonemes"].append({
            "phoneme": ph,
            "raw_similarity": raw_sim,
            "score": final_score,
            "grade": grade,
            "color": color,
            "start": entry["start"],
            "end": entry["end"]
        })
        
        total_score += final_score
        count += 1

    # Push last word
    if current_word_obj:
        w_scores = [p["score"] for p in current_word_obj["phonemes"]]
        current_word_obj["word_score"] = int(np.mean(w_scores)) if w_scores else 0
        grade, color = get_grade(current_word_obj["word_score"])
        current_word_obj["grade"] = grade
        current_word_obj["color"] = color
        final_report["details"].append(current_word_obj)

    # Final Average
    final_report["overall_score"] = int(total_score / count) if count > 0 else 0
    
    # Save
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        json.dump(final_report, f, indent=2)

    print(f"\n[SUCCESS] Generated Assessment Report: {OUT_FILE}")
    print(f"Overall Score: {final_report['overall_score']}/100")

if __name__ == "__main__":
    main()